// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VideoManage.EFCore
{
    public partial class VCountries
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
    }
}