// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VideoManage.EFCore
{
    public partial class WCostinfo
    {
        public int Id { get; set; }
        /// <summary>
        /// 用户编号
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 水费
        /// </summary>
        public string WaterMoney { get; set; }
        /// <summary>
        /// 电费
        /// </summary>
        public string ElectricMoney { get; set; }
        /// <summary>
        /// 物业费
        /// </summary>
        public string SerMoney { get; set; }
        /// <summary>
        /// 停车费
        /// </summary>
        public string StoMoney { get; set; }
        /// <summary>
        /// 煤气费
        /// </summary>
        public string CoalMoney { get; set; }
        /// <summary>
        /// 缴费时间
        /// </summary>
        public DateTime? CreateTime { get; set; }
    }
}