// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VideoManage.EFCore
{
    /// <summary>
    /// 房屋信息表
    /// </summary>
    public partial class WHouseinfo
    {
        public int Id { get; set; }
        /// <summary>
        /// 房屋地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 房屋户型
        /// </summary>
        public int? HouseType { get; set; }
        /// <summary>
        /// 房屋面积
        /// </summary>
        public string HouseArea { get; set; }
        /// <summary>
        /// 入住人数
        /// </summary>
        public int? Number { get; set; }
    }
}