// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VideoManage.EFCore
{
    public partial class WRepairinfo
    {
        public int Id { get; set; }
        /// <summary>
        /// 保修地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 业主编号
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 提交时间
        /// </summary>
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// 维修时间
        /// </summary>
        public DateTime? RepairTime { get; set; }
    }
}